version: '3.1'
# Docker setup
# https://medium.com/@crocodile2u/docker-setup-for-a-laravel-vue-project-90e4fd3acc7a
# Vue/laravel
# https://pusher.com/tutorials/laravel-vue-axios

services:
  www:
    image: nginx:alpine
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: backend
      dockerfile: backend.dockerfile
    # this way container interacts with host on behalf of current user.
    # !!! NOTE: $UID is a _shell_ variable, not an environment variable!
    # To make it available as a shell var, make sure you have this in your ~/.bashrc (./.zshrc etc):
    # export UID="$UID"
    user: ${UID}:${UID}
    volumes:
      - ./backend/laravel:/app
      # custom adjustments to php.ini
      # i. e. "xdebug.remote_host" to debug the dockerized app
      - ./etc/php:/usr/local/etc/php/local.conf.d/
    environment:
      # add our custom config files for the php to scan
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8080"

  frontend:
    image: node:current-alpine
    user: ${UID}:${UID}
    working_dir: /home/node/app
    volumes:
    - ./frontend/app:/home/node/app
    environment:
      NODE_ENV: development
    command: "npm run serve"
